endpoints:
  - http://localhost:9650/ext/bc/C/rpc
  - http://localhost:9652/ext/bc/C/rpc
  - http://localhost:9658/ext/bc/C/rpc
  - http://localhost:9656/ext/bc/C/rpc
  - http://localhost:9654/ext/bc/C/rpc
base-fee: 25
priority-fee: 1
concurrency: 10