uris:
  - http://127.0.0.1:9650/ext/bc/C
  - http://127.0.0.1:9652/ext/bc/C
  - http://127.0.0.1:9654/ext/bc/C
  - http://127.0.0.1:9658/ext/bc/C
  - http://127.0.0.1:9656/ext/bc/C
base-fee: 30
priority-fee: 1
concurrency: 10